newsweek magazine clone
che30/Newsweek-clone pull request #1
Opened 2020-10-17 21:41 UTC by che30

I implemented the following 
- The navbar 
- The different sections 
- The footer . All these using bootstrap framework

2020-10-18 18:53 UTC, arslanbisharat requested changes
# Status: REQUIRED CHANGES :warning: :construction: 
Hi che30
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).
##
 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] please remove commented code. 
- [ ] Remove `!important `from **main.css** file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)

- [ ] Please add Newsweek in the navbar
- [ ] There are text **overlapping** and **Responsive web design** issues in all sections. Please implement  RWD breakpoints like the original lading page
### Footer
- [ ] Please manage the width and height Logo
- [ ] Please update the social icons like the original web page
- [ ] Text of copyright should be horizontal with  logo
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/96376690-e7b50200-1199-11eb-844f-63d02aa8b674.png)|![clone](https://user-images.githubusercontent.com/29689273/96376693-eedc1000-1199-11eb-8d37-2397aafbfcd5.png)|
##
- **When you have made the specified changes, please submit another code review. Thank you!**

Regards,
Arslan Bisharat 
slack : arslanbisharat

2020-10-19 13:23 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @che30
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##
For this project, we have to make sure nothing is messed up. Kindly work on the suggested change  👇.
- [ ] The project is working fine locally but not online. Please Correct it. 
Instead of  `<link rel="stylesheet" href="/assets/stylesheets/main.css">`
It should be `<link rel="stylesheet" href="./assets/stylesheets/main.css">`

##

- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-19 13:57 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @che30  . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The Twitter account appears as suspended, please change it to a working account or delete from the README.

- [ ] The license link is broken in the README.

- [ ] The website is using the Bootstrap CDN, an the css directory files are not needed anymore. Please remove them

- [ ] There should be one css directory with the main or all needed stylesheets. 

- [ ] All images should have an alternative text atributte. Please make sure all ```<img>``` tags have an ```alt``` attribute with a short and meaningful description of the picture.

- [ ] The page should have one ```<h1>``` tag. This helps SEO.

- [ ] There is no significant difference in the 983px and 985px please choose one and merge them together

- [ ] In the "in the magazine" section one element is different than the others but is not appearing in the clone.

- [ ] There is one extra element in the "in the magazine" section on desktop view.
![image](https://user-images.githubusercontent.com/25774518/96459245-87e54800-11e7-11eb-88c6-58d157f797fb.png)

- [ ] The "editor pick" section elements are missing description and category in the image corner
![image](https://user-images.githubusercontent.com/25774518/96459405-b400c900-11e7-11eb-8e25-66832e11c3fb.png)
![image](https://user-images.githubusercontent.com/25774518/96459486-ca0e8980-11e7-11eb-9640-2b7de841c9ad.png)

- [ ] Footer doesn't look like the original
![image](https://user-images.githubusercontent.com/25774518/96459640-f4604700-11e7-11eb-8c16-b5aea3b8255c.png)

- [ ] Category section doesn't look as expected in tablet view
![image](https://user-images.githubusercontent.com/25774518/96459809-296c9980-11e8-11eb-9a76-3d5156971af2.png)

- [ ] Newsletter section doesn't look as expected, the text alignment and the margins of the input. in tablet view
![image](https://user-images.githubusercontent.com/25774518/96459924-4739fe80-11e8-11eb-89aa-e6345b289843.png)

- [ ] Footer doesn't look as expected in tablet view
![image](https://user-images.githubusercontent.com/25774518/96460071-72bce900-11e8-11eb-97c0-fa17bc55fca0.png)

- [ ] Navbar doesn't look as expected in mobile view

- [ ] The order of the sections in mobile view is not correct. The original starts with top story, the clone with featured stories

- [ ] Image not rendering 
![image](https://user-images.githubusercontent.com/25774518/96460330-b7488480-11e8-11eb-80ee-9eaacd9d3f34.png)

- [ ] More stories element doesn't match original, image is overlaping and text is not surrounding the image
![image](https://user-images.githubusercontent.com/25774518/96460459-d515e980-11e8-11eb-931d-6de2fd99512a.png)

- [ ] Newsletter element is not centered and is going out of the website boundaries
![image](https://user-images.githubusercontent.com/25774518/96460552-f1198b00-11e8-11eb-881a-feee2bb6bfb9.png)

- [ ] Subscribe section doesn't look like original on mobile version
![image](https://user-images.githubusercontent.com/25774518/96460652-0b536900-11e9-11eb-8562-cea6b4fbfa64.png)

- [ ] Footer doesn't look as expected 
![image](https://user-images.githubusercontent.com/25774518/96460777-350c9000-11e9-11eb-93e8-3879b3a601c3.png)


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-20 12:18 UTC, Rhelli requested changes
# Changes Required 🛑♻️

Hi @che30, congratulations on the project so far, you've managed to create an excellent clone and your documentation and Readme is likewise, excellent. There are however a few changes that need to be made in order to get this project approved. If you correct these errors, we'll be able to get you approved and onto the next project!

## 📝  Readme Changes 

**[Mandatory]**  - Please remove the incorrect title and description for the NextWeb project as seen below 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96579476-d4578300-12ce-11eb-8e6c-1cd85d9893a8.png)


**[Mandatory]** -  Please make the description to your project in your Readme (the text that appears directly beneath your title) more descriptive. There's a lot to say about this project and you've done a lot to create it, so tell everyone about it! 

I'd suggest summarising the process you went through to create the project, the technologies you used and the overall objectives of the project as a starter. Remember - this is the first thing people see when they look at your project - your goal is to keep them interested enough to look further into your project! 👀



**[Mandatory]** -  The screenshot is excellent and I always recommend it. However I would only screenshot a portion, not the entire page. At the moment your Readme is mostly screenshot! 


**[Optional]** - If you want to show off your project quickly, make a gif and attach it to you Readme. It's more compact (space-wise), more interactive and more eye catching. If you want to know more, [have a look at this tutorial on adding gifs to your Readme.](https://medium.com/@josephcardillo/how-to-add-gifs-to-your-github-readme-89c74da2ce47)


**[Mandatory]** -  There previous TSE addressed the fact that your Readme currently has a broken License link at the end. Please fix this by adding a `LICENSE.txt` file to your Readme. Use [this website](https://choosealicense.com/) to copy and paste a standard license. Easy as pie! 🥧


**[Optional]** -  I wouldn't recommend adding yourself as an Acknowledgement after you've already listed yourself as the author. They're the same thing!

*******

## 👨🏽‍💻 Code Changes

**[Mandatory]** - The previous TSE addressed the issue of none of your links (`<a href>`) having the required `alt` tags. Please add them with a brief description to all of your links. Being able to create accessible HTML is a sought after skill, so best to learn it!



**[Mandatory]** -  The previous TSE pointed out that you should only have one `h1` tag in your HTML and he is completely right. I can currently see 3 different `h1` tags so please downgrade 2 of these to `h2` and reserve the most important title of the page for `h1`.



**[Mandatory]** -  Please amend your 'In The Magazine' section 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96581860-5d23ee00-12d2-11eb-89c8-66d3dde3b792.png)

There's two issues to point out here
 1. Please remove the newsline that appears beneath the 'See All Features' section. It does not appear in the original.

2. Please fix the images - they are the wrong height and it is creating a large amount of whitespace which should not be present. I suspect this has happened because you are using the wrong images, which are the wrong ratio and aren't tall enough. To fix this, just download the new NextWeb images (or use the url links) and this section should appear more compact.

For reference, this is what the 'In The Magazine' section should look like 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96582296-fc48e580-12d2-11eb-9c01-8125db9fbc0f.png)




**[Mandatory]** -  As suggested by the previous TSE, your 'Editors Pick' section is still missing the topic/category in the bottom right hand corner of the image. This **also** occurs on small screen sizes. Here is your version 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96582456-387c4600-12d3-11eb-9ab1-0335ba46306f.png)

Here is what it should look like 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96582742-a7599f00-12d3-11eb-8bd8-ea9b08e07b1f.png)




**[Mandatory]** - Please fix your footer. You're nearly there with it, there's just a few tweaks to make to make it perfect! Currently, your footer looks like this 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96582717-990b8300-12d3-11eb-930c-c93cf037461f.png)

It should look closer to this 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96582843-c5bf9a80-12d3-11eb-897f-ec73150f6f06.png)

How to fix it? Easy!
1. Give the 'Editions' and 'About Us | Corrections.. etc' divs `padding` on the sides.
2. Give your 'Editions' countries text (i.e. 'U.S. Edition | Pakistan ... etc') a `margin-right` property.
3. Give the '© 2020 NEWSWEEK DIGITAL LLC' element a property of `margin-top: auto` to align it with the 'Newsweek' logo.
4. Check your LinkedIn logo - its different from the rest of the logos in size and color.



**[Mandatory]** - I'm afraid your categories on tablet size screens still need a little work - your not far off though! Here is your version 👇🏽

![image](https://user-images.githubusercontent.com/48107460/96583410-94939a00-12d4-11eb-9b96-bfae9240dd3f.png)
 
The issue here is the `font-sizes` are too large, particularly for the images on the right hand side. Reduce the font sizes and increase the image sizes. The LinkedIn logo **also dissapears** on tablet screen sizes. For reference, this is what it should look like

![image](https://user-images.githubusercontent.com/48107460/96583560-cf95cd80-12d4-11eb-8fcb-e696bd1ca5bd.png)

******


Thats it! Get those errors fixed and you'll be onto the next project in no time. Again, excellent work on the project so far. You've managed to create the clone with a minimal amount of custom CSS, your CSS is **super** clean and your HTML is well organised! Make these changes and you'll have a stellar project for your portfolio! 🌟 Good luck!

If you need any help, @ me on Github or feel free to reach out to me via Slack.

All the best,

💂🏽‍♂️ Rory👀

2020-10-20 19:39 UTC, descholar-ceo requested changes
# Status: Change required :warning: :recycle:
## :wave: :wave: :wave: Hello @che30  :vertical_traffic_light: You are almost there with this big project.
You have done a great job so far, congratulations on that.
- I liked that you used some semantic HTML,
- And that you tried your best to use CSS best practices, keep that up :muscle: :muscle:

However you need to fix few things to make it on the standard.
### The comment marked as __[Required]__ must be implemented to get the project approved, the other marked as __[Optional]__ aren't compulsory to get this project approved.

## Required changes :red_circle:
- [ ] As it is mentioned with the previous TSEs, I would recommend you to use descriptive `alt` attributes on all `<img/>` elements. Currently you are using links on them, which is not good. Use something like ` alt="name of a user`
- [x] Make sure that your footer is properly fixed as mentioned by the previous TSEs
Clone: 
![Screenshot from 2020-10-20 20-57-59](https://user-images.githubusercontent.com/56886064/96631799-186e7600-1317-11eb-8129-22c2c05e5af3.png)
Original: 
![Screenshot from 2020-10-20 20-59-38](https://user-images.githubusercontent.com/56886064/96631879-320fbd80-1317-11eb-8d82-c245b6faa28c.png)

- [x] Fix the subscribe section because it doesn't look like original on mobile version
Your version: 
![Screenshot from 2020-10-20 21-13-09](https://user-images.githubusercontent.com/56886064/96633438-66847900-1319-11eb-84a8-b7b5b212a1c6.png)

Original version:
![Screenshot from 2020-10-20 21-13-47](https://user-images.githubusercontent.com/56886064/96633469-6e441d80-1319-11eb-8115-8723ca77b96a.png)

- [x] The newsletter section is almost done, but it nees some spacing around the form, 
Your version: 
![Screenshot from 2020-10-20 21-16-51](https://user-images.githubusercontent.com/56886064/96633695-c1b66b80-1319-11eb-8995-3f0702c307ec.png)
Original version: 
![Screenshot from 2020-10-20 21-18-39](https://user-images.githubusercontent.com/56886064/96633759-db57b300-1319-11eb-8dc8-2abfa8bfd577.png)

## Optional changes :large_blue_circle:
- [ ] The pictures that are on more stories section, make them abit big, 
Your version:
![Screenshot from 2020-10-20 21-21-08](https://user-images.githubusercontent.com/56886064/96634120-55883780-131a-11eb-896f-d4eedc6d2d9f.png)

Original version:
![Screenshot from 2020-10-20 21-22-36](https://user-images.githubusercontent.com/56886064/96634168-68027100-131a-11eb-8b48-5067b4d7c586.png)

- [ ] I noticed that on mobile screens your navbar needs a bit of work
currently it looks like this: 
![Screenshot from 2020-10-20 21-05-50](https://user-images.githubusercontent.com/56886064/96632475-0f31d900-1318-11eb-9a80-46d5f4b1c1dc.png)
It should look like this:
![Screenshot from 2020-10-20 21-06-31](https://user-images.githubusercontent.com/56886064/96632541-27095d00-1318-11eb-82c8-2b4103bd0fc8.png)


- [ ] As requested by the previous TSEs, it would be better if you remove yourself from the acknowledgement section

- [ ] Read all other comments I added directly in your codes

:point_right: Make all the above requested changes, and submit an other code review request

If you have something which appears to you as unclear, don't hesitate to reach me out on slack as `@Mugirase Emmanuel` | [LinkedIn](https://www.linkedin.com/m/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by: Mugirase Emmanuel (descholar)

2020-10-20 19:39 UTC, descholar-ceo commented on README.md
> +## The purpose of the project is to test microverse students mastery of the bootsrap framework and ensure they build responsive webpages across the following viewports. Large screens(laptots) medium
Here you can just use usual text, there is no need to make it a title, since you already have a title

2020-10-20 19:39 UTC, descholar-ceo commented on README.md
> +- LinkedIn: [Che Blanchard](https://www.linkedin.com/in/che-nsoh-9455271b0/)
Since we have other acknowledgement below, I would recommend you to get rid of this one

2020-10-20 19:39 UTC, descholar-ceo commented on assets/stylesheets/main.css
> +  border-bottom: 1px solid#f4f5f7;
I guess that here you forgot to add some space between `solid#f4f5f7`

2020-10-20 19:39 UTC, descholar-ceo commented on index.html
> +                      class="width-100" alt="	https://d.newsweek.com/en/full/1654388/libresco.png?w=63&h=63&f=d5f8d9cc3f1ca8e1c176e6d9344905f4">
I would recommend you to use the descriptive `alt` on `<img/>` elements as it is suggested with other TSEs

2020-10-20 19:39 UTC, descholar-ceo commented on index.html
> +                      class="width-100" alt="	https://d.newsweek.com/en/full/1654388/libresco.png?w=63&h=63&f=d5f8d9cc3f1ca8e1c176e6d9344905f4">
I would recommend you to use the descriptive `alt` on `<img/>` elements as it is suggested with other TSEs

2020-10-20 19:39 UTC, descholar-ceo commented on index.html
> +                      class="width-100" alt="	https://d.newsweek.com/en/full/1654388/libresco.png?w=63&h=63&f=d5f8d9cc3f1ca8e1c176e6d9344905f4">
I would recommend you to use the descriptive `alt` on `<img/>` elements as it is suggested with other TSEs

2020-10-20 22:37 UTC, descholar-ceo requested changes
# Status: Change required :warning: :recycle:
## :wave: :wave: :wave: Hello @che30 :vertical_traffic_light: Your progress is very good and you are very close to the project approval
You have done a great job so far, congratulations on that.
:+1: You fixed the navbar on mobile, that is very good, I like it.
### However you need to implement all the required changes as they are required in the previous reviews. Kindly check all of them and implement them one by one untill you make it.

:point_right: Make all the above requested changes, and submit an other code review request

:pager: If you have something which appears to you as unclear, don't hesitate to reach me out on slack as @Mugirase Emmanuel | [LinkedIn](https://www.linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Happy coding!

2020-10-21 11:24 UTC, che30 commented on README.md
> +## The purpose of the project is to test microverse students mastery of the bootsrap framework and ensure they build responsive webpages across the following viewports. Large screens(laptots) medium
All changes checked above have been implemented as required

2020-10-21 12:32 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @che30 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] You have repeated the description in the README file two times. Please remove the following text from the README file. The next description is awesome. (Please visit the [image](https://user-images.githubusercontent.com/29689273/96719786-4f01ca80-13c3-11eb-8413-d3387f6ca129.png))

```
## The next web
## A responsive web design based on The newsweek website made for learning purposes.
```
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-21 12:41 UTC, che30 commented
> # Status: REQUIRED CHANGES  
> Hi @che30
> Good job with the changes!  We are almost there.
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below  and work on the suggested changes.
> 
> * [ ]  You have repeated the description in the README file two times. Please remove the following text from the README file. The next description is awesome. (Please visit the [image](https://user-images.githubusercontent.com/29689273/96719786-4f01ca80-13c3-11eb-8413-d3387f6ca129.png))
> 
> ```
> ## The next web
> ## A responsive web design based on The newsweek website made for learning purposes.
> ```
> 
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
> HAPPY CODING 
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)
Deleted redundant text in readme

2020-10-21 15:12 UTC, jubaan approved these changes
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

### [Observations]

- [ ] There are some minor stylelint issues, please fix them before merging.

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

2020-10-21 15:16 UTC, merged